export default function DeepfakeProject() {
  return (
    <main className="max-w-3xl mx-auto px-6 py-28 space-y-12">

      {/* TITLE */}
      <div>
        <h1 className="text-3xl font-semibold tracking-tight mb-4">
          Robust Detection of AI-Generated Images Across Generative Models
        </h1>

        <p className="text-gray-600 leading-relaxed">
          A comparative study and evaluation framework for detecting synthetic images 
          generated by GANs, diffusion models, and transformer-based systems, with a 
          focus on robustness under real-world distortions.
        </p>
      </div>

      {/* PROBLEM */}
      <div>
        <h2 className="text-xl font-semibold mb-3">Problem</h2>
        <p className="text-gray-600 leading-relaxed">
          Existing detection systems often fail to generalize across different generative 
          models and degrade significantly under common image transformations such as 
          compression and blur. Most approaches are tightly coupled to specific datasets 
          or model families, limiting real-world applicability.
        </p>
      </div>

      {/* APPROACH */}
      <div>
        <h2 className="text-xl font-semibold mb-3">Approach</h2>
        <p className="text-gray-600 leading-relaxed">
          Designed a structured evaluation framework to systematically compare multiple 
          detection paradigms across diverse generative model outputs.
        </p>

        <ul className="mt-4 space-y-2 text-gray-600 text-sm">
          <li>• Artifact-based detection (visual inconsistencies)</li>
          <li>• Frequency-domain analysis (spectrum-based methods)</li>
          <li>• Encoder-based models (CNNs, Vision Transformers, CLIP)</li>
          <li>• Cross-model evaluation across GANs, diffusion, and transformer outputs</li>
        </ul>
      </div>

      {/* SYSTEM DESIGN */}
      <div>
        <h2 className="text-xl font-semibold mb-3">Evaluation Pipeline</h2>
        <div className="text-sm text-gray-600 border border-gray-200 rounded-lg p-4 leading-relaxed">
          Input: Real + AI-generated images (GAN, diffusion, transformer) <br />
          → Detection Models (CNN / ViT / CLIP / Frequency-based) <br />
          → Robustness Testing (compression, blur) <br />
          → Output: Performance metrics + failure analysis
        </div>
      </div>

      {/* DATA */}
      <div>
        <h2 className="text-xl font-semibold mb-3">Datasets</h2>
        <p className="text-sm text-gray-600 leading-relaxed">
          Combined real-world image datasets with synthetic data generated from multiple 
          model families, enabling cross-distribution evaluation and robustness testing.
        </p>
      </div>

      {/* EVALUATION */}
      <div>
        <h2 className="text-xl font-semibold mb-3">Evaluation</h2>
        <ul className="text-sm text-gray-600 space-y-2">
          <li>• Accuracy, Precision, Recall, F1-score</li>
          <li>• Robustness under JPEG compression and Gaussian blur</li>
          <li>• Feature interpretability using Grad-CAM</li>
          <li>• Representation analysis using t-SNE</li>
        </ul>
      </div>

      {/* KEY INSIGHTS */}
      <div>
        <h2 className="text-xl font-semibold mb-3">Key Insights</h2>
        <ul className="text-sm text-gray-600 space-y-2">
          <li>• No single detection method generalizes across all generative models</li>
          <li>• Frequency-based methods show robustness but lower adaptability</li>
          <li>• Transformer-based models perform well but are sensitive to distortions</li>
          <li>• Hybrid approaches are necessary for real-world deployment</li>
        </ul>
      </div>

      {/* IMPACT */}
      <div>
        <h2 className="text-xl font-semibold mb-3">Impact</h2>
        <ul className="text-sm text-gray-600 space-y-2">
          <li>• Improves understanding of AI-generated image detection limitations</li>
          <li>• Contributes to AI safety and misinformation mitigation</li>
          <li>• Provides foundation for robust, real-world detection systems</li>
        </ul>
      </div>

      {/* STACK */}
      <div>
        <h2 className="text-xl font-semibold mb-3">Technical Stack</h2>
        <p className="text-sm text-gray-600">
          PyTorch · Computer Vision · Vision Transformers · CLIP · 
          Grad-CAM · t-SNE · Image Processing
        </p>
      </div>

    </main>
  );
}